CREATE TABLE attractions
(
    attraction_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name          VARCHAR(255),
    creation_date DATE,
    description   VARCHAR(500),
    type          VARCHAR(255),
    city_id       BIGINT
);

CREATE TABLE cities
(
    city_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    population BIGINT,
    has_metro  BOOLEAN
);

CREATE TABLE activities
(
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name        VARCHAR(255),
    description VARCHAR(500)
);

CREATE TABLE attractions_activities
(
    attraction_id BIGINT NOT NULL,
    activity_id   BIGINT NOT NULL,
    CONSTRAINT fk_attractions_activities_attraction FOREIGN KEY (attraction_id) REFERENCES attractions(attraction_id),
    CONSTRAINT fk_attractions_activities_activity FOREIGN KEY (activity_id) REFERENCES activities(activity_id)
);
